---
- hosts: mywebserver
  become: yes
  tasks:
  - name: i want execute linux directly
    commands: hostname -f
    register: mylinuxcmd 
  - name: i want to display first task result
    debug: 
      msg: "{{mylinuxcmd}}"  
  
