---
- hosts: mywebserver
  become: yes
  tasks:
  - name: i want to execute linux directly
    commands: hostname -f
    register: mylinuxcmd 
  - name: i want to debug
    debug: 
      msg: "{{mylinuxcmd}}"  
  
