---
- hosts: 172.31.11.206
  become: yes
  tasks:
  - name: execute linux directly
    commands: hostname -f
    register: mylinuxcmd 
  - name: i want to display first task result
    debug: 
      msg: "{{mylinuxcmd}}"  
  
