---
- hosts: mywebserver
  become: yes
  tasks:
   - name: execute linux commands
     command: hostname -f
     register: mydebugresult
  
   - name: i want to display my tasks
     debug:
       msg: "{{mydebugresult}}"

   - name: install git 
     apt: 
       name: git
       state: present
     when: mydebugresult.stderr =="" 

   - name: install tree
     yum:
       name: tree
       state: present
     when: mydebugresult.stderr ==""    