---
- hosts: mywebserver
  become: yes
  tasks:
  - name: install java on ubuntu nodes
    apt:
      name: openjdk-8-jdk
      state: present
    when: ansible_os_family =="Debian"


  - name: install java on redhat nodes
    apt:
      name: java-1.8.0-openjdk
      state: present
    when: ansible_os_family =="RedHat"