---
- hosts: mywebserver
  become: yes
  vars:
   myvars01: git
   myvars02: wget
   myvars03: tree
   myvars04: nginx
  tasks:
  - name: i want to display myvars04
    debug:
      msg: "{{myvars04}}"
      
  - name: install java on ubuntu nodes
    apt:
      name: "{{myjavaonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"


  - name: install java on redhat nodes
    yum:
      name: "{{myjavaonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"

