---
- hosts: mywebserver
  become: yes
  tasks:
  - name: i want install webserver on ubuntu nodes
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"  




  - name: i want start webserver on ubuntu nodes
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family =="Debian"  


  - name: i want install webserver on RedHat nodes
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"


  - name: i want start webserver on RedHat nodes
    service: 
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family =="RedHat"